### ISSUE TITLE
503 service unavailable

### ISSUE THREAD

**Issue by stuttboksa** [envato/envato-wordpress-toolkit#82]
Hi!

I have installed the plugin and activated it. When I try to open it the page loads really slow and after a while i get the following message: 
"Error 503 Service Unavailable
Service Unavailable
XID: 1048685307"

It is 100% related to the plugin because it only happens when it's installed.

I use a theme called Native Church.

elimtistedal.no

**Comment by AndonDesign** [comment]
noticed similar thing with the Envato API connectivity this morning. 
Was able to fix it by adding a "User-Agent" to the <code>remote_request()</code> function located in "class-engato-api.php", right here:
![2015-07-05_14-44-34](https://cloud.githubusercontent.com/assets/12068636/8512877/7e6e18c2-2324-11e5-87dc-d4903d6a1e02.png)
This is the line I added:
<code>'user-agent' => 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0',</code>

Now, I don't know to what extend this is related to your issue but thought I'd share in case that it is, or hopefully useful to other users.

I remember a few months back Envato made it mandatory to specify "user-agents" in API requests, so that could be it.

Cheers

**Comment by stuttboksa** [comment]
Thanks for the reply. I have no idea on what to do with the information you just sent me... Not sure what my issue has to do with mozilla or windows. I use Safari or Chrome on my Mac but thats probably irrelevant.

**Comment by shawnlunny** [comment]
@AndonDesign Is this a fix for the interim before the new plugin version comes out? Is this something you can release just to keep users stable?

**Comment by AndonDesign** [comment]
@shawnlunny I'm not officially involved with this plugin, just thought I'd share my findings. Someone who's in charge with the plugin development here could potentially evaluate the information I provided, test it and decide whether to make it an official release.
Regards

**Comment by shawnlunny** [comment]
@valendesigns Is this a fix for the interim before the new plugin version comes out? Is this something you can release just to keep users stable?

**Comment by shawnlunny** [comment]
Sorry @AndonDesign wrong callout. Thanks for the patch though.

**Comment by docwisdom** [comment]
+1 here with the same issue. 
Confirmed by moving the plugin out of the plugins folder. Only affects admin panel access after login session is created.
WP 4.2.2

**Comment by valendesigns** [comment]
I believe the API connection issues can be solved by adding a user agent, which didn't use to be a requirement for what it's worth. Though from my understanding the devs are working on a solution that doesn't force everyone to update the plugin.

**Comment by valendesigns** [comment]
Latest version solves this issue.

**Comment by AndonDesign** [comment]
Good to know :)

--
Andon
andon.design@gmail.com
